# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert_c <- function(colour, from, to) {
    .Call('_farver_convert_c', PACKAGE = 'farver', colour, from, to)
}

